// Bibliothèque de plantes (version condensée — enrichissez si besoin)
export const PLANT_LIBRARY = [
  { name: "Monstera Deliciosa", latin: "Monstera deliciosa", type: "Intérieur", light: "Lumière vive indirecte", water: "Modéré (1×/semaine)", description: "Grande plante tropicale aux feuilles fendues spectaculaires.", care: { temperature: "18-27°C", humidity: "Élevée (60%+)", soil: "Riche et drainant", fertilizer: "Liquide 1×/15j en été", repot: "Tous les 2 ans" }, plantation: "Pot avec trous de drainage, 5 cm plus large que la motte, billes d'argile au fond.", propagation: "Bouturage : tige sous un nœud avec racine aérienne dans l'eau.", tips: ["Nettoyer les feuilles régulièrement", "Tuteur de mousse", "Ne pas couper les racines aériennes", "Tourner le pot chaque semaine"], problems: ["Feuilles jaunes : excès d'eau", "Non fendues : manque de lumière", "Bouts bruns : air sec"] },
  { name: "Pothos doré", latin: "Epipremnum aureum", type: "Intérieur", light: "Lumière vive indirecte à faible", water: "Modéré (1×/semaine)", description: "Plante grimpante ou retombante ultra-facile, idéale débutants.", care: { temperature: "15-27°C", humidity: "Modérée", soil: "Terreau universel", fertilizer: "1×/mois en croissance", repot: "Tous les 2-3 ans" }, plantation: "Sur une étagère en hauteur pour l'effet retombant.", propagation: "Bouturage dans l'eau très facile.", tips: ["Quasi indestructible", "Tolère les oublis", "Plus de lumière = plus de panachure"], problems: ["Feuilles entièrement vertes : manque lumière", "Pointes brunes : eau calcaire"] },
  { name: "Ficus Elastica", latin: "Ficus elastica", type: "Intérieur", light: "Lumière vive indirecte", water: "Modéré (1×/semaine)", description: "Arbre caoutchouc aux grandes feuilles épaisses brillantes.", care: { temperature: "16-24°C", humidity: "Modérée", soil: "Terreau riche drainant", fertilizer: "Dilué tous les 15j avr-sept", repot: "Tous les 2-3 ans" }, plantation: "À 1-2 m d'une fenêtre est ou ouest.", propagation: "Bouturage d'extrémité avec hormone.", tips: ["Essuyer feuilles tous les 15j", "Tailler en mars", "Sève laiteuse irritante"], problems: ["Perte feuilles du bas : normal", "Taches brunes : eau calcaire"] },
  { name: "Sansevieria", latin: "Dracaena trifasciata", type: "Intérieur", light: "Tolère tout", water: "Rare (tous les 3 semaines)", description: "Plante succulente aux feuilles raides, la plus résistante qui existe.", care: { temperature: "15-27°C", humidity: "Aime l'air sec", soil: "Terreau cactées", fertilizer: "Cactées 2×/an", repot: "Tous les 3-4 ans" }, plantation: "Pot en terre cuite, drainage obligatoire.", propagation: "Division de la touffe au printemps.", tips: ["Quasi indestructible", "Oublier plutôt que noyer", "Produit de l'oxygène la nuit"], problems: ["Feuilles molles : pourriture racines", "Pointes sèches : eau calcaire"] },
  { name: "Orchidée Phalaenopsis", latin: "Phalaenopsis sp.", type: "Intérieur", light: "Lumière vive indirecte", water: "Espacé (tous les 10-15j)", description: "Orchidée papillon, floraison longue et spectaculaire.", care: { temperature: "18-25°C jour, 15-18°C nuit", humidity: "50-70%", soil: "Écorces orchidées", fertilizer: "Orchidées 1×/mois", repot: "Tous les 2-3 ans" }, plantation: "Pot transparent obligatoire (racines photosynthèse).", propagation: "Keikis (rejets) sur hampe florale.", tips: ["Bain 15 min eau tiède", "Couper hampe après floraison", "Racines vertes = hydratées"], problems: ["Feuilles molles : racines asphyxiées", "Pas de floraison : manque écart thermique"] },
  { name: "Aloe Vera", latin: "Aloe barbadensis", type: "Succulente", light: "Plein soleil", water: "Rare (tous les 3 semaines)", description: "Succulente médicinale aux vertus cicatrisantes.", care: { temperature: "15-27°C, gélive", humidity: "Faible", soil: "Terreau cactées", fertilizer: "Cactées au printemps", repot: "Tous les 2-3 ans" }, plantation: "Pot terre cuite percé, drainage indispensable.", propagation: "Séparation des rejets au printemps.", tips: ["Sécher entre arrosages", "Feuilles plissées = sec", "Gel soulage brûlures"], problems: ["Pourriture : excès d'eau", "Brûlures : lumière brutale"] },
  { name: "Cactus", latin: "Echinocactus grusonii", type: "Succulente", light: "Plein soleil", water: "Très rare (1×/mois)", description: "Cactus globuleux, longévité exceptionnelle.", care: { temperature: "10-30°C été, 8-12°C repos hivernal", humidity: "Très faible", soil: "Cactées très drainant", fertilizer: "2-3× printemps-été", repot: "Tous les 3-4 ans" }, plantation: "Pot terre cuite, gravier + substrat drainant.", propagation: "Semis lent ou rejets.", tips: ["Arroser seulement si sec", "Arrêter l'hiver", "Soleil maximal"], problems: ["Pourriture base : excès eau", "Étiolement : manque lumière"] },
  { name: "Pommier", latin: "Malus domestica", type: "Fruitier", light: "Plein soleil", water: "Modéré", description: "Arbre fruitier rustique, pollinisateur requis.", care: { temperature: "Rustique -25°C", humidity: "Peu exigeant", soil: "Profond, drainé, pH 6-6.5", fertilizer: "Compost automne + engrais printemps", repot: "Plantation automne hors gel" }, plantation: "Trou 60×60×60, tuteur avant l'arbre, collet au niveau du sol.", propagation: "Greffage en écusson en août.", harvest: "Juillet-octobre selon variété. Conservation 4-6 mois cave fraîche.", companions: "Capucine, œillet d'Inde, ciboulette. Variété pollinisatrice INDISPENSABLE.", tips: ["Tailler en hiver hors gel", "Éclaircir fruits en juin", "Bouillie bordelaise automne", "Pièges phéromones carpocapse"], problems: ["Tavelure", "Carpocapse (vers)", "Pucerons cendrés", "Oïdium"] },
  { name: "Citronnier", latin: "Citrus × limon", type: "Fruitier", light: "Plein soleil", water: "Modéré", description: "Agrume méditerranéen persistant, fleurs très parfumées.", care: { temperature: "5-30°C, protéger <-2°C", humidity: "Modérée", soil: "Terreau agrumes", fertilizer: "Agrumes mars-octobre", repot: "Tous les 2-3 ans" }, plantation: "Bac profond 40 cm min, billes d'argile, plein sud.", propagation: "Marcottage aérien ou bouturage semi-ligneux été.", harvest: "Échelonnée toute l'année selon variété.", companions: "Ail, ciboulette au pied.", tips: ["Rentrer hiver 5-10°C", "Sortir après gelées", "Eau non calcaire", "Tailler en mars"], problems: ["Chlorose", "Chute fruits : stress hydrique", "Cochenilles"] },
  { name: "Figuier", latin: "Ficus carica", type: "Fruitier", light: "Plein soleil", water: "Espacé", description: "Arbre méditerranéen rustique aux fruits délicieux.", care: { temperature: "Rustique -15°C", humidity: "Résiste sécheresse", soil: "Tout sol drainé", fertilizer: "Compost automne", repot: "Automne ou printemps" }, plantation: "Plein sud abrité par mur, contenir racines si besoin.", propagation: "Bouturage février sur bois d'un an, très facile.", harvest: "Variétés bifères : juin-juillet et août-septembre.", tips: ["Variétés bifères : 2 récoltes", "Protéger vent froid", "Tailler peu"], problems: ["Figues vertes qui tombent : stress", "Cochenilles"] },
  { name: "Basilic", latin: "Ocimum basilicum", type: "Aromatique", light: "Plein soleil", water: "Fréquent (2-3×/semaine)", description: "Aromatique annuelle méditerranéenne.", care: { temperature: "20-30°C, gélif", humidity: "Modérée", soil: "Riche, drainant", fertilizer: "Inutile si terre riche", repot: "Semis mars" }, plantation: "Après Saints de Glace (mi-mai), espacer 20 cm.", propagation: "Semis ou bouture dans l'eau (1 semaine).", harvest: "Juin aux gelées. Cueillir le matin.", companions: "Tomate (repousse mouche blanche), poivron.", tips: ["Pincer les sommités", "Supprimer les fleurs", "Cueillir le matin"], problems: ["Noircissement : froid", "Pourriture : excès d'eau"] },
  { name: "Menthe", latin: "Mentha spp.", type: "Aromatique", light: "Soleil à mi-ombre", water: "Fréquent", description: "Aromatique vivace envahissante, à contenir en pot.", care: { temperature: "Rustique", humidity: "Aime l'humidité", soil: "Frais, riche", fertilizer: "Peu nécessaire", repot: "Diviser tous les 2 ans" }, plantation: "Impérativement en pot ou conteneur sans fond.", propagation: "Division très facile, bouture dans l'eau.", harvest: "Mai-septembre, avant floraison.", companions: "Repousse pucerons, mouche du chou.", tips: ["TOUJOURS en pot : envahissante", "Rabattre en septembre", "Avant floraison"], problems: ["Rouille : couper et brûler"] },
  { name: "Lavande", latin: "Lavandula angustifolia", type: "Aromatique", light: "Plein soleil", water: "Rare", description: "Arbustive méditerranéenne, attire pollinisateurs.", care: { temperature: "Rustique -15°C", humidity: "Sec", soil: "Pauvre, calcaire, drainant", fertilizer: "AUCUN", repot: "Printemps ou automne" }, plantation: "Plein sud, sol drainé, gravier dans le trou.", propagation: "Bouturage en août quasi infaillible.", harvest: "Juin-juillet à l'ouverture des fleurs.", companions: "Rosiers (repousse pucerons).", tips: ["Tailler après floraison", "Gravier à la plantation", "Bouturer en août"], problems: ["Jaunissement : trop d'eau", "S'évase : tailler"] },
  { name: "Thym", latin: "Thymus vulgaris", type: "Aromatique", light: "Plein soleil", water: "Très rare", description: "Sous-arbrisseau méditerranéen persistant.", care: { temperature: "Rustique", humidity: "Sec", soil: "Pauvre, caillouteux", fertilizer: "Aucun", repot: "Bouturage" }, plantation: "Plein sud, rocaille idéale.", propagation: "Semis, bouturage été, division.", harvest: "Toute l'année, arôme max en juin.", companions: "Repousse piérides du chou.", tips: ["Sol pauvre = meilleur parfum", "Tailler après floraison", "Diviser tous les 3-4 ans"], problems: ["Jaunissement : excès d'eau"] },
  { name: "Romarin", latin: "Salvia rosmarinus", type: "Aromatique", light: "Plein soleil", water: "Rare", description: "Arbuste persistant à fleurs bleues hivernales.", care: { temperature: "Rustique -10°C", humidity: "Sec", soil: "Pauvre, calcaire", fertilizer: "Aucun", repot: "Tous les 3-4 ans" }, plantation: "Plein sud abrité des vents froids.", propagation: "Bouturage août très facile.", harvest: "Toute l'année.", companions: "Repousse mouche de la carotte.", tips: ["Tailler en mars après floraison", "Jamais dans le vieux bois", "Floraison hiver = abeilles"], problems: ["Brun et sec : excès eau ou gel"] },
  { name: "Persil", latin: "Petroselinum crispum", type: "Aromatique", light: "Soleil à mi-ombre", water: "Régulier", description: "Bisannuelle cultivée comme annuelle.", care: { temperature: "10-25°C", humidity: "Modérée", soil: "Riche, frais", fertilizer: "Compost plantation", repot: "Semis mars-juillet" }, plantation: "Semis direct, tremper graines 24h.", propagation: "Uniquement semis.", harvest: "2 mois à 1 an. Feuilles extérieures.", companions: "Tomate, carotte.", tips: ["Tremper graines la veille", "Semis échelonné mensuel", "Feuilles extérieures seulement"], problems: ["Germination ratée : graines vieilles", "Montée graines : chaleur"] },
  { name: "Ciboulette", latin: "Allium schoenoprasum", type: "Aromatique", light: "Soleil à mi-ombre", water: "Régulier", description: "Vivace de la famille oignon, fleurs comestibles.", care: { temperature: "Rustique -20°C", humidity: "Modérée", soil: "Riche, drainé", fertilizer: "Compost léger", repot: "Diviser tous les 3 ans" }, plantation: "Semis avril-juin, espacer 25 cm.", propagation: "Division touffes au printemps.", harvest: "Avril-novembre, 2-3 cm du sol.", companions: "Repousse pucerons des rosiers.", tips: ["Couper souvent", "Fleurs comestibles", "Diviser tous les 3-4 ans"], problems: ["Rouille rare", "Dégarnit : diviser"] },
  { name: "Tomate", latin: "Solanum lycopersicum", type: "Potager", light: "Plein soleil", water: "Régulier au pied", description: "Légume-fruit incontournable du potager.", care: { temperature: "18-27°C, gélif", humidity: "Sèche sur feuilles", soil: "Riche, drainé, pH 6-6.8", fertilizer: "Compost + purin ortie/consoude", repot: "Semis février" }, plantation: "Après 15 mai, enterrer la tige, tuteur immédiat.", propagation: "Semis en godet février-mars.", harvest: "Juillet-octobre, à pleine maturité.", companions: "Basilic, œillet d'Inde, carotte, persil. Éviter pomme de terre.", tips: ["Tuteurer dès plantation", "Supprimer gourmands", "Arroser au pied matin", "Pailler généreusement"], problems: ["Mildiou", "Cul noir (calcium)", "Pucerons", "Fruits fendus : à-coups arrosage"] },
  { name: "Courgette", latin: "Cucurbita pepo", type: "Potager", light: "Plein soleil", water: "Abondant", description: "Très productive, fleurs comestibles.", care: { temperature: "20-30°C, gélif", humidity: "Modérée", soil: "Riche, profond, frais", fertilizer: "Compost abondant", repot: "Semis avril godet" }, plantation: "Mi-mai, trou de 40 cm, compost. Espacer 1 m.", propagation: "Semis direct ou godet.", harvest: "Juin-octobre, cueillir jeunes (15-20 cm).", companions: "Haricot, maïs, capucine. Éviter concombre.", tips: ["1 pied nourrit 4", "Fleurs mâles en beignets", "Paillage obligatoire"], problems: ["Oïdium août", "Pourriture : pailler dessous", "Fruits avortent : polliniser main"] },
  { name: "Salade", latin: "Lactuca sativa", type: "Potager", light: "Soleil matin", water: "Régulier", description: "Légume-feuille à cycle rapide.", care: { temperature: "10-20°C, monte à graines >25°C", humidity: "Sol frais", soil: "Frais, riche, léger", fertilizer: "Compost plantation", repot: "Semis mars-septembre" }, plantation: "Repiquer à 25 cm, ne pas enterrer collet.", propagation: "Par semis.", harvest: "6 sem à 3 mois selon variété.", companions: "Radis, carotte, fraise, chou.", tips: ["Échelonner semis tous les 15j", "Ombrage léger été", "Récolte matin"], problems: ["Montée graines : chaleur", "Limaces", "Mildiou : espacer"] },
  { name: "Radis", latin: "Raphanus sativus", type: "Potager", light: "Soleil à mi-ombre", water: "Régulier", description: "Légume-racine ultra-rapide (3-4 semaines).", care: { temperature: "10-20°C", humidity: "Sol frais", soil: "Léger, sableux", fertilizer: "Pas nécessaire", repot: "Semis direct" }, plantation: "Semis direct en ligne, éclaircir à 5 cm.", propagation: "Semis.", harvest: "3-4 semaines, ne pas laisser trop (creux).", companions: "Carotte, laitue, concombre.", tips: ["Idéal débutants", "Arroser régulièrement", "Semis entre cultures lentes"], problems: ["Piquants/creux : manque eau", "Altises : voile"] },
  { name: "Fraisier", latin: "Fragaria × ananassa", type: "Fruitier", light: "Soleil à mi-ombre", water: "Régulier", description: "Petit fruit rouge, variétés remontantes ou non.", care: { temperature: "Rustique -15°C", humidity: "Modérée", soil: "Humus, drainé, pH 5.5-6.5", fertilizer: "Compost + engrais fraisier", repot: "Renouveler tous les 3-4 ans" }, plantation: "Août-septembre, espacer 30-40 cm. Pailler.", propagation: "Stolons très facile.", harvest: "Mai-septembre selon variété.", companions: "Épinard, ail, oignon, haricot. Éviter chou, tomate.", tips: ["Pailler sous les fruits", "Filet anti-oiseaux", "Renouveler tous les 3 ans"], problems: ["Pourriture grise : aérer", "Limaces", "Oïdium"] },
  { name: "Rosier", latin: "Rosa sp.", type: "Fleur", light: "Plein soleil (6h min)", water: "Modéré régulier", description: "Reine des jardins, nombreuses variétés.", care: { temperature: "Rustique", humidity: "Sèche sur feuilles", soil: "Profond, riche, drainé", fertilizer: "Engrais rosiers printemps/été", repot: "Automne/hiver hors gel" }, plantation: "Trou 50×50, compost, point greffe au niveau du sol.", propagation: "Bouturage août ou greffage.", harvest: "Fleurs coupées le matin.", companions: "Lavande, ail, ciboulette, œillet d'Inde.", tips: ["Tailler en mars", "Supprimer fleurs fanées", "Arroser au pied matin", "Bouillie bordelaise préventive"], problems: ["Marsonia (taches noires)", "Oïdium", "Pucerons", "Rouille"] },
  { name: "Géranium (Pelargonium)", latin: "Pelargonium sp.", type: "Fleur", light: "Plein soleil", water: "Modéré été, espacé hiver", description: "Plante de balcon florifère, non rustique.", care: { temperature: "Gélif", humidity: "Modérée", soil: "Terreau géraniums", fertilizer: "Géraniums 1×/semaine été", repot: "Printemps" }, plantation: "Balconnières après mi-mai.", propagation: "Bouturage extrêmement facile août.", tips: ["Supprimer fleurs fanées", "Rentrer hiver 5-10°C", "Tailler court en mars"], problems: ["Papillon géranium (mineuse)", "Rouille", "Pourriture hiver"] },
  { name: "Pivoine", latin: "Paeonia lactiflora", type: "Fleur", light: "Soleil à mi-ombre", water: "Modéré", description: "Vivace majestueuse, floraison mai-juin, 50 ans+.", care: { temperature: "Rustique -20°C", humidity: "Modérée", soil: "Profond, riche, drainé", fertilizer: "Compost printemps", repot: "N'aime pas être déplacée" }, plantation: "Yeux à 2-3 cm MAX sous la surface (critique).", propagation: "Division tous les 5-6 ans.", tips: ["Ne JAMAIS enterrer profondément", "Ne pas déplacer", "Tuteurer grosses fleurs"], problems: ["Pas de floraison : trop enterrée", "Botrytis : couper"] },
  { name: "Tulipe", latin: "Tulipa sp.", type: "Fleur", light: "Soleil", water: "Modéré plantation", description: "Bulbeuse printanière, floraison avril-mai.", care: { temperature: "Hiver froid requis", humidity: "Modérée", soil: "Drainé, pas trop lourd", fertilizer: "Compost automne", repot: "Plantation oct-nov" }, plantation: "Octobre-novembre, 3× hauteur du bulbe, pointe haute.", propagation: "Caïeux à l'arrachage.", tips: ["Plantation oct-nov IMPÉRATIVE", "Laisser feuillage jaunir", "Protéger campagnols (panier)"], problems: ["Campagnols : panier grillagé", "Pas de refloraison : feuillage coupé tôt"] },
  { name: "Hortensia", latin: "Hydrangea macrophylla", type: "Fleur", light: "Mi-ombre", water: "Abondant", description: "Arbuste à grosses inflorescences, couleur selon pH.", care: { temperature: "Rustique -15°C", humidity: "Aime humidité", soil: "Frais, riche, acide pour bleu", fertilizer: "Hortensias printemps", repot: "Automne ou printemps" }, plantation: "Mi-ombre, compost + terre bruyère si bleu voulu.", propagation: "Bouturage août.", tips: ["BLEU : sol acide + aluminium", "ROSE : sol calcaire", "Arroser impérativement été", "Tailler en mars"], problems: ["Sec en été : arroser urgent", "Chlorose : sol calcaire", "Pas de floraison : tailles mal placées"] }
];

// Symptômes groupés par catégorie
export const SYMPTOMS = [
  { id: 'wilting', label: 'Feuilles molles et flétries', cat: 'Apparence' },
  { id: 'falling_leaves', label: 'Chute des feuilles', cat: 'Apparence' },
  { id: 'slow_growth', label: 'Croissance très lente', cat: 'Apparence' },
  { id: 'etiolation', label: 'Tiges longues et pâles', cat: 'Apparence' },
  { id: 'stunted_growth', label: 'Plante rabougrie', cat: 'Apparence' },
  { id: 'yellow_leaves', label: 'Feuilles jaunes', cat: 'Feuilles' },
  { id: 'pale_leaves', label: 'Feuilles pâles', cat: 'Feuilles' },
  { id: 'brown_edges', label: 'Bordures brunes', cat: 'Feuilles' },
  { id: 'yellow_veins', label: 'Nervures vertes, feuille jaune', cat: 'Feuilles' },
  { id: 'brown_spots', label: 'Taches brunes', cat: 'Feuilles' },
  { id: 'black_spots', label: 'Taches noires', cat: 'Feuilles' },
  { id: 'red_spots', label: 'Taches rouges/orange', cat: 'Feuilles' },
  { id: 'yellow_spots', label: 'Taches jaunes circulaires', cat: 'Feuilles' },
  { id: 'oily_spots', label: 'Taches huileuses', cat: 'Feuilles' },
  { id: 'white_powder', label: 'Poudre/duvet blanc dessus', cat: 'Feuilles' },
  { id: 'fuzzy_underside', label: 'Duvet sous les feuilles', cat: 'Feuilles' },
  { id: 'curled_leaves', label: 'Feuilles enroulées', cat: 'Feuilles' },
  { id: 'dry_crispy', label: 'Bouts secs/craquants', cat: 'Feuilles' },
  { id: 'holes_in_leaves', label: 'Trous dans les feuilles', cat: 'Feuilles' },
  { id: 'skeleton_leaves', label: 'Feuilles réduites aux nervures', cat: 'Feuilles' },
  { id: 'visible_insects', label: 'Insectes visibles', cat: 'Bêtes' },
  { id: 'webs', label: 'Toiles fines', cat: 'Bêtes' },
  { id: 'white_fuzzy_clumps', label: 'Amas blancs cotonneux', cat: 'Bêtes' },
  { id: 'white_flies', label: 'Mouches blanches', cat: 'Bêtes' },
  { id: 'sticky_substance', label: 'Substance collante', cat: 'Bêtes' },
  { id: 'ants', label: 'Fourmis sur la plante', cat: 'Bêtes' },
  { id: 'black_roots', label: 'Racines noires ou molles', cat: 'Sol & racines' },
  { id: 'bad_smell', label: 'Odeur désagréable du terreau', cat: 'Sol & racines' },
  { id: 'mold_soil', label: 'Moisissure sur le terreau', cat: 'Sol & racines' },
  { id: 'stem_rot', label: 'Tige qui pourrit à la base', cat: 'Sol & racines' },
  { id: 'soft_stems', label: 'Tiges molles', cat: 'Tige' },
  { id: 'cracked_bark', label: 'Écorce craquelée', cat: 'Tige' },
  { id: 'cankers', label: 'Plaies/chancres', cat: 'Tige' },
  { id: 'no_flowers', label: 'Absence de floraison', cat: 'Fleurs & fruits' },
  { id: 'dropped_buds', label: 'Boutons qui tombent', cat: 'Fleurs & fruits' },
  { id: 'fruit_drop', label: 'Chute prématurée des fruits', cat: 'Fleurs & fruits' },
  { id: 'deformed_fruit', label: 'Fruits déformés', cat: 'Fleurs & fruits' },
  { id: 'rotting_fruit', label: 'Fruits qui pourrissent sur l\'arbre', cat: 'Fleurs & fruits' },
  { id: 'black_bottom_fruit', label: 'Fond des fruits noir (tomates)', cat: 'Fleurs & fruits' }
];

// Diagnostics avec remèdes
export const DIAGNOSES = [
  { name: "Excès d'arrosage / racines pourries", symptoms: ['yellow_leaves', 'wilting', 'black_roots', 'falling_leaves', 'stem_rot', 'bad_smell', 'mold_soil', 'soft_stems'], cause: "Racines asphyxiées qui pourrissent.", remedies: ["Arrêter immédiatement l'arrosage", "Laisser sécher plusieurs jours", "Dépoter si pourriture, couper racines noires, rempoter sec", "Vérifier drainage", "Reprendre quand 2-3 cm secs"] },
  { name: "Manque d'arrosage", symptoms: ['wilting', 'dry_crispy', 'falling_leaves', 'curled_leaves', 'brown_edges', 'stunted_growth'], cause: "Sécheresse : tissus déshydratés.", remedies: ["Bassiner 15-20 min eau tiède", "Reprendre arrosage régulier", "Pailler la surface", "Éloigner des radiateurs"] },
  { name: "Oïdium", symptoms: ['white_powder', 'pale_leaves', 'curled_leaves', 'stunted_growth'], cause: "Champignon voile blanc poudreux (chaleur + humidité nocturne).", remedies: ["Bicarbonate 5g/L + savon noir", "Soufre mouillable (<25°C)", "Décoction de prêle", "Espacer les plants", "Arroser au pied"] },
  { name: "Mildiou", symptoms: ['brown_spots', 'yellow_leaves', 'wilting', 'oily_spots', 'fuzzy_underside', 'rotting_fruit'], cause: "Champignon par humidité persistante. Redoutable tomates.", remedies: ["Bouillie bordelaise préventive 3× à 15j", "Décoction de prêle ou consoude", "Supprimer et BRÛLER parties atteintes", "Aérer, pailler", "Arroser au pied matin"] },
  { name: "Pucerons", symptoms: ['sticky_substance', 'curled_leaves', 'visible_insects', 'slow_growth', 'ants'], cause: "Petits insectes qui sucent la sève.", remedies: ["Jet d'eau puissant", "Savon noir (2 c.s./L)", "Purin d'ortie 10%", "Coccinelles", "Capucine à proximité"] },
  { name: "Araignées rouges", symptoms: ['pale_leaves', 'webs', 'yellow_leaves', 'dry_crispy', 'yellow_spots'], cause: "Acariens par air sec et chaud.", remedies: ["Brumiser quotidiennement", "Doucher la plante", "Décoction d'ail", "Billes d'argile humides sous pot"] },
  { name: "Cochenilles farineuses", symptoms: ['sticky_substance', 'slow_growth', 'white_fuzzy_clumps', 'yellow_leaves'], cause: "Amas blancs cotonneux ou boucliers bruns.", remedies: ["Coton imbibé d'alcool 70°", "Savon noir + huile colza + alcool", "Isoler la plante", "Répéter 3 semaines"] },
  { name: "Aleurodes (mouches blanches)", symptoms: ['white_flies', 'sticky_substance', 'yellow_leaves', 'slow_growth'], cause: "Petits insectes blancs en nuées, sous feuilles.", remedies: ["Pièges chromatiques jaunes", "Savon noir répété", "Purin de fougère", "Basilic compagnon", "Aspirateur main tôt le matin"] },
  { name: "Thrips", symptoms: ['pale_leaves', 'yellow_spots', 'deformed_fruit', 'dropped_buds', 'slow_growth'], cause: "Insectes minuscules qui piquent feuilles et fleurs.", remedies: ["Pièges chromatiques bleus", "Douches régulières", "Savon noir + huile neem", "Isoler la plante"] },
  { name: "Chenilles / limaces / escargots", symptoms: ['holes_in_leaves', 'visible_insects', 'skeleton_leaves'], cause: "Feuilles rongées.", remedies: ["Ramassage manuel le soir", "Cendres, coquilles d'œufs", "Pièges à bière", "Bacillus thuringiensis", "Favoriser hérissons oiseaux"] },
  { name: "Carence en azote", symptoms: ['pale_leaves', 'yellow_leaves', 'slow_growth', 'stunted_growth'], cause: "Jaunissement des VIEILLES feuilles d'abord.", remedies: ["Compost bien mûr en surface", "Purin d'ortie au 10e", "Corne broyée, sang séché", "Engrais NPK équilibré"] },
  { name: "Chlorose (carence fer)", symptoms: ['yellow_veins', 'pale_leaves', 'yellow_leaves', 'slow_growth'], cause: "Nervures vertes, feuilles jaunes. Sol calcaire.", remedies: ["Chélate de fer", "Purin d'ortie", "Terre de bruyère, marc de café", "Eau de pluie"] },
  { name: "Carence en potassium", symptoms: ['brown_edges', 'yellow_leaves', 'no_flowers', 'deformed_fruit', 'fruit_drop'], cause: "Bordures qui jaunissent puis brunissent.", remedies: ["Cendres de bois tamisées", "Purin de consoude", "Patentkali", "Compost avec déchets cuisine"] },
  { name: "Manque de lumière", symptoms: ['pale_leaves', 'slow_growth', 'falling_leaves', 'no_flowers', 'etiolation'], cause: "Souffrance lumineuse.", remedies: ["Déplacer près fenêtre", "Tourner le pot", "Lampe horticole l'hiver", "Nettoyer vitres et feuilles"] },
  { name: "Brûlures solaires", symptoms: ['brown_spots', 'dry_crispy', 'curled_leaves', 'yellow_spots'], cause: "Feuilles brûlées par soleil direct.", remedies: ["Déplacer à l'ombre/filtrer", "Arroser matin/soir", "Supprimer feuilles abîmées", "Acclimater progressivement"] },
  { name: "Marsonia / taches noires rosier", symptoms: ['black_spots', 'yellow_leaves', 'falling_leaves'], cause: "Maladie fongique rosiers et fruitiers.", remedies: ["Ramasser et BRÛLER feuilles tombées", "Bouillie bordelaise dès débourrement", "Décoction de prêle 2 sem.", "Tailler aéré"] },
  { name: "Rouille", symptoms: ['red_spots', 'yellow_leaves', 'falling_leaves'], cause: "Pustules rouge-orange au revers.", remedies: ["Supprimer et BRÛLER", "Décoction de prêle ou soufre", "Bouillie bordelaise préventive", "Pas d'humidité sur feuillage"] },
  { name: "Pourriture grise (Botrytis)", symptoms: ['rotting_fruit', 'brown_spots', 'dropped_buds'], cause: "Duvet gris poudreux sur parties tendres.", remedies: ["Aérer maximum", "Supprimer et brûler", "Pas d'arrosage soir", "Décoction de prêle", "Éclaircir plants"] },
  { name: "Moniliose (fruitiers)", symptoms: ['rotting_fruit', 'cankers', 'brown_spots'], cause: "Fruits qui pourrissent sur l'arbre (cerisier, prunier).", remedies: ["Ramasser et BRÛLER fruits momifiés", "Bouillie bordelaise chute feuilles + débourrement", "Éclaircir branches", "Éviter blessures"] },
  { name: "Cul noir (tomates)", symptoms: ['black_bottom_fruit', 'deformed_fruit'], cause: "Carence calcium par arrosage irrégulier.", remedies: ["Arroser RÉGULIÈREMENT", "Pailler épais", "Coquilles d'œufs broyées", "Éviter excès azote"] },
  { name: "Excès d'engrais", symptoms: ['brown_edges', 'dry_crispy', 'stunted_growth', 'yellow_leaves'], cause: "Sels qui brûlent les racines.", remedies: ["Rincer terreau à grande eau plusieurs fois", "Arrêter fertilisation 2 mois", "Rempoter si grave", "Engrais dilué régulier"] },
  { name: "Choc d'acclimatation", symptoms: ['falling_leaves', 'yellow_leaves', 'wilting', 'dropped_buds'], cause: "Changement brutal récent.", remedies: ["Laisser 2-3 semaines sans intervenir", "Arrosage régulier modéré", "Éviter courants d'air", "Pas de fertilisation"] },
  { name: "Pollinisation insuffisante", symptoms: ['fruit_drop', 'no_flowers', 'deformed_fruit'], cause: "Manque de pollinisateurs ou variété incompatible.", remedies: ["Variété pollinisatrice compatible", "Favoriser pollinisateurs", "Pas d'insecticides en fleur", "Polliniser au pinceau"] },
  { name: "Chancre (arbres fruitiers)", symptoms: ['cankers', 'cracked_bark', 'falling_leaves'], cause: "Lésions brunes sur l'écorce.", remedies: ["Couper 20 cm sous la lésion", "Brûler les résidus", "Désinfecter outils (alcool)", "Mastic cicatrisant", "Bouillie bordelaise automne/printemps"] },
  { name: "Nématodes", symptoms: ['stunted_growth', 'yellow_leaves', 'wilting', 'deformed_fruit'], cause: "Vers microscopiques sur racines.", remedies: ["Planter œillets d'Inde (Tagetes)", "Rotation 4 ans", "Compost (biodiversité)", "Solarisation été", "Supprimer et brûler plants"] }
];

export const SEASONS = [
  { id: 'hiver', months: [11, 0, 1], name: "Hiver", tasks: ["Tailler fruitiers hors gel", "Protéger du gel", "Pailler arbustes fragiles", "Réduire arrosages intérieur", "Nettoyer les outils", "Planifier le potager", "Semer sous abri fin février"] },
  { id: 'printemps', months: [2, 3, 4], name: "Printemps", tasks: ["Rempoter plantes intérieur", "Reprendre engrais", "Tailler rosiers", "Semer salades et radis", "Planter arbres et arbustes", "Traiter fruitiers", "Éclaircir les semis"] },
  { id: 'ete', months: [5, 6, 7], name: "Été", tasks: ["Arroser tôt le matin", "Pailler abondamment", "Pincer gourmands tomates", "Tailler les haies", "Récolter régulièrement", "Surveiller maladies", "Cueillir et sécher aromatiques"] },
  { id: 'automne', months: [8, 9, 10], name: "Automne", tasks: ["Planter arbres fruitiers", "Récolter et stocker", "Ramasser feuilles malades", "Semer engrais verts", "Composter", "Planter bulbes printemps", "Rentrer plantes gélives"] }
];

// Tâches saisonnières par type de plante : pour chaque plante de l'herbier,
// on sait quoi faire selon la saison.
export const TASKS_BY_TYPE = {
  'Fruitier': {
    hiver: ["Tailler hors gel (décembre-février)", "Badigeon de blanc arboricole sur le tronc", "Bouillie bordelaise préventive", "Ramasser les fruits momifiés restants", "Pailler le pied"],
    printemps: ["Surveiller l'apparition des pucerons", "Éclaircir les fruits en juin", "Apport de compost au pied", "Traiter préventivement contre la tavelure", "Installer pièges phéromones"],
    ete: ["Arroser en profondeur au pied (pas sur les feuilles)", "Surveiller carpocapse et cochenilles", "Éclaircir si surcharge", "Récolter au fur et à mesure"],
    automne: ["Récolter les derniers fruits", "Ramasser les feuilles malades (brûler)", "Bouillie bordelaise à la chute des feuilles", "Plantation possible hors gel", "Préparer les protections hivernales"]
  },
  'Potager': {
    hiver: ["Planifier les rotations", "Commander les graines", "Préparer les semis sous abri (février)", "Nettoyer et affûter les outils", "Enrichir le sol avec du compost"],
    printemps: ["Semer tomates/courgettes/poivrons sous abri", "Préparer les planches (grelinette)", "Repiquer après les Saints de Glace (15 mai)", "Pailler dès installation", "Semer salades, radis, carottes"],
    ete: ["Arroser au pied le matin (pas sur les feuilles)", "Pailler épais (paille, tontes)", "Pincer les gourmands des tomates", "Récolter régulièrement", "Surveiller mildiou et oïdium"],
    automne: ["Récolter les dernières tomates (vertes à l'abri)", "Arracher plants fatigués (composter si sains)", "Semer des engrais verts (phacélie, moutarde)", "Pailler épais pour l'hiver", "Planter ail et oignons"]
  },
  'Aromatique': {
    hiver: ["Protéger romarin et thym des vents froids", "Rabattre la menthe au sol", "Récolter en journée hors gel", "Rentrer le basilic si survivant"],
    printemps: ["Semer basilic sous abri (mars)", "Diviser la ciboulette", "Rempoter les aromatiques en pot", "Bouturer thym et romarin", "Tailler romarin/lavande après floraison"],
    ete: ["Cueillir régulièrement tôt le matin", "Pincer les sommités pour ramifier", "Supprimer les fleurs (sauf si grainage)", "Arroser le basilic (pas romarin/thym)"],
    automne: ["Récolter et faire sécher (bouquets à l'envers)", "Bouturer thym/romarin/lavande", "Rentrer le basilic (gélif)", "Rabattre la menthe"]
  },
  'Intérieur': {
    hiver: ["Réduire fortement les arrosages", "Éloigner des radiateurs (air sec)", "Brumiser le feuillage régulièrement", "Pas d'engrais (repos végétatif)", "Tourner le pot chaque semaine"],
    printemps: ["Rempoter si racines à l'étroit", "Reprendre l'engrais (1×/15 jours)", "Dépoussiérer les feuilles", "Bouturer si souhaité", "Déplacer à la meilleure lumière"],
    ete: ["Sortir sur balcon ombré si possible", "Arroser plus fréquemment", "Engrais liquide tous les 15 jours", "Brumiser par forte chaleur", "Surveiller araignées rouges"],
    automne: ["Rentrer les plantes sorties (avant 10°C)", "Diminuer progressivement l'engrais", "Réduire les arrosages", "Surveiller cochenilles et pucerons"]
  },
  'Succulente': {
    hiver: ["Arrêter quasi totalement les arrosages", "Placer dans une pièce fraîche (10-15°C)", "Maximum de lumière", "Pas d'engrais"],
    printemps: ["Reprendre les arrosages progressivement", "Rempoter si nécessaire (substrat cactées)", "Engrais spécial cactées 1×/mois", "Séparer les rejets pour multiplier"],
    ete: ["Arroser uniquement si le substrat est TOTALEMENT sec", "Plein soleil OK (acclimater)", "Protéger des pluies excessives", "Engrais tous les 15 jours"],
    automne: ["Diminuer les arrosages", "Rentrer avant les gelées", "Stopper l'engrais", "Placer au frais et lumineux"]
  },
  'Fleur': {
    hiver: ["Protéger vivaces gélives (voile, paillage)", "Tailler les rosiers (fin février - mars)", "Planter tulipes/narcisses (avant décembre)", "Nettoyer les massifs"],
    printemps: ["Tailler les rosiers si pas fait", "Diviser les vivaces", "Tuteurer pivoines et dahlias", "Engrais rosiers", "Planter bulbes d'été (dahlias, glaïeuls)"],
    ete: ["Supprimer les fleurs fanées régulièrement", "Arroser au pied le matin", "Surveiller oïdium, taches noires, pucerons", "Bouturer rosiers en août"],
    automne: ["Planter les bulbes de printemps (octobre)", "Rabattre les vivaces", "Pailler les pieds pour l'hiver", "Diviser les pivoines (si nécessaire)"]
  },
  'Extérieur': {
    hiver: ["Protéger du gel (voile d'hivernage)", "Pailler épais au pied", "Tailler hors gel si besoin", "Nettoyer et ranger les outils"],
    printemps: ["Rempoter si cultivé en pot", "Reprendre l'engrais", "Surveiller les parasites", "Arroser à la reprise de végétation", "Tailler les arbustes à floraison estivale"],
    ete: ["Arroser tôt le matin ou le soir", "Pailler pour conserver l'humidité", "Ombrer les jeunes plants", "Surveiller les maladies par temps humide"],
    automne: ["Rentrer les plantes gélives en pot", "Pailler tous les pieds", "Composter les feuilles saines", "Planter arbres et arbustes rustiques"]
  }
};

// Fonction utilitaire : retourne les tâches d'une plante pour une saison donnée.
// Prend en compte le type de la plante.
export function getTasksForPlant(plant, seasonId) {
  if (!plant || !plant.type || !seasonId) return [];
  const typeTasks = TASKS_BY_TYPE[plant.type];
  if (!typeTasks) return [];
  return typeTasks[seasonId] || [];
}
